version: '3.9'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile

    container_name: playground_django_tdd
    
    ports:
      - 0.0.0.0:8000:8000

    volumes:
      - ./workspace:/workspace

    command: /bin/sh # -c "while sleep 1000; do :; done"      
